name: smartstore
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
#  sdk: '>=2.0.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  curved_navigation_bar: ^1.0.6
  dio: ^5.8.0+1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  flutter_localization: ^0.3.2
  flutter_gemini: ^3.0.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  skeletonizer: ^0.4.0
  equatable: ^2.0.7
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/
    - assets/temp/
    - assets/temp/beauty.png
    - assets/icons/






  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300